global:
    scrape_interval: 10s
  
scrape_configs:
    - job_name: 'backend_micrometer'
      metrics_path: '/actuator/prometheus'
      scrape_interval: 5s
      static_configs:
        - targets: ['backend:8080']